### ISSUE TITLE
Windows WebView without external DLLs

### ISSUE THREAD

**Issue by falkTX** [lucianoiam/hiphop#4]
Just saw this, might be useful for you https://github.com/Tracktion/choc/blob/main/gui/choc_WebView.h

a way to not have to install webview addons, by embedding the DLL in the code and loading it from memory.

if unwanted, feel free to close

**Comment by lucianoiam** [comment]
Hi, very interesting stuff, thanks. Also like how the Mac web view calls ObjC APIs without needing a mm file ...

Fully self-contained plugin binaries would be great to have when the format/platform combination does not specify a filesystem structure. That also requires to bundle web assets, leaving some ideas in descendent coolness:

- Intercept HTTP requests from the web views and serve memory instead (not sure all platforms support this)
- Serve memory files using libwebsockets (ok but forces plugins to enable the web server)
- Create files in a temp location and load using file:/// from there  (lo-fi but works)

For the time being I'm focusing on creating a plugin but leaving this open.

**Comment by lucianoiam** [comment]
I spent some time looking at CHOC's code and it is clever. But it is also more complex than expected and does not add much value here. Therefore I am sticking to DPF's minimalist mantra :)

Thanks a lot for sharing this!
